[project]
name = "LibESN"
description = "Python library for single and multi-frequency ESN models"
readme = "README.md"
requires-python = ">=3.9"
license = { text="GPL-3.0" }
# authors = [{name = "?", email = "?"}]
dynamic = ["version"]

dependencies = [
    "numpy >= 1.26.0",
    "pandas >= 2.2",
    "matplotlib >= 3.8",
    "numba >= 0.59",
    "scipy >= 1.12",
    "rich >= 13.7",
    "pymoo >= 0.6.1",
    "cvxopt >= 1.3",
    "qpsolvers >= 4.3",
    "pdoc >= 14.4",
]

[project.urls]
Source = "https://github.com/RCEconModelling/LibESN"
# Documentation = "https://?"
Issues = "https://github.com/RCEconModelling/LibESN/issues"

[build-system]
requires = ["setuptools"]

[tool.setuptools.packages.find]
include = ["LibESN*"]